services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: composer install --no-dev --optimize-autoloader && mkdir -p var/cache/twig && chmod -R 755 var/
    startCommand: php -S 0.0.0.0:$PORT public/index.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: RENDER
        value: true