services:
  - type: web
    name: HNG-stage-2--twig
    
 env: php
 plan: free
 buildCommand: composer install --no-dev --optimize-autoloader
 startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: RENDER
        value: true
      - key: NODE_ENV
        value: production
